#this is a python script made for windows 10, 11 and android v1-12
import math
import time
time.sleep(2)
print ("This file was halted by 2 seconds should we try 3?")
time.sleep(3)
print ("This part of the file was halted by 3 seconds, should we try 5?")
time.sleep(5)
print ("After 5 seconds we can understand that this looks like its almost crashed, lets try 10 seconds")
time.sleep(10)
print ("After 10 seconds we can understand that the files could almost break, so lets try around 50 seconds")
time.sleep(1)
print ("You ready?")
time.sleep(1)
print ("3")
time.sleep(1)
print ("2")
time.sleep(1)
print ("1")
time.sleep(1)
print ("okay, we will now pause the system for 50 seconds, dont worry the software has not crashed unless an error message appears")
time.sleep(50)
print ("Told you it hadn't crashed")
time.sleep(4)
print ("This file is run on python3 and is developed by Phr0ph3cy!")
